print("Hoy es martes 10 de enero de 2023")
print("Estoy bastante bien, podría estar mejor")
print("En 2 meses he aprendido a programar algunas cosas con el print")
print("Hola Miguel del futuro UwU")
print("<3")